### ISSUE TITLE
Bug with snkr

### ISSUE THREAD

**Issue by manueltarouca** [ussaohelcim/snkr#1]
Once the snake eats 3 squares, if we shake the mouse the snake eats itself blocking the game.
![image](https://user-images.githubusercontent.com/36767065/180327296-e8b84a88-4bea-4288-8710-36159366a5b4.png)

**Comment by ussaohelcim** [comment]
Its a feature, you are supposed to die when you hit yourself. It only works after 3 points because my code sucks.  
Just refresh the game to start again.

**Comment by manueltarouca** [comment]
ok
